server:
  port: 8092

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driverClassName: org.h2.Driver
    username: test_user
    password: testing

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/db-changelog-master.xml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-query-params-without-oauth2: true